### ISSUE TITLE
Bad IDs in Mongo cause do not result in errors but null objects during unmarshaling

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/core-metadata#30]
The Java code erroneously allows a Device Service to get created with a null Addressable because the address id in the Device Service record is not in the database.  This is obviously not a desirable situation and should result in a marshaling error (as it does in the Go Lang code).  This same issue may happen with other marshaling/unmarshaling of other domain objects.
It was detected during the black box tests.  The device with ID: '57fe0a4ce4b060e2df0aa10f' (line 510 of deviceDb.json) references the device service with ID: '57fddb0de4b060e2df0aa105' (line 402 of deviceserviceDb.json) which referenced an addressable with ID: '57fdda80e4b060e2df0aa102' which doesn't exist in addressableDb.json.  
This causes the unmarshaling of the device service in Go Lang to fail which in turn causes the device unmarshal to fail.

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
