### ISSUE TITLE
Name for addressable can be 'null' and also stored

### ISSUE THREAD

**Issue by devFallingstar** [edgexfoundry/core-metadata#31]
When I send a request to `http://localhost:48081/api/v1/addressable` to make new addressable information, with empty raw-body(`{}`) it returns correct addressable ID(like `5ad57af725ac2ee36085c33f`) even there's no name value.

Also, when I send a same request with same body(`{}`), it shows error with `Improper data: Name is not unique: null`

I think it have to check the name data in request body is null or not.

<img width="807" alt="error" src="https://user-images.githubusercontent.com/23091621/38849035-49c2e150-4245-11e8-8266-104124a1ab79.png">

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
