### ISSUE TITLE
Error responses to REST API calls include full stack traces

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/core-metadata#7]
When interacting with the metadata service using curl, I noticed that when an error response is returned, a stack trace is returned in addition to the status code.  Other than the initial Exception class message, this stack trace isn't useful to the client.

My guess is that this bug actually applies to all of the Java/Spring frameworks code, however as I'm not aware of a project-wide Issues tracker, I've filed this against the metadata service, as it's where I first encountered the bug.

Taking a look at best practices for REST APIs, there seem to be many approaches to returning errors:

 * Use HTTP-only Status Codes
 * Use HTTP Status + JSON body
 * Ignore HTTP Status and only use JSON body

It appears that presently, EdgeX is using the first approach, but additionally returning extra information a raw text.

Steps to reproduce (using Ubuntu 16.04 Desktop):

1) Create a new dummy addressable object:
$ STATUS=$(curl -w "%{http_code}" -H 'Content-Type: application/json' -d '{"id":null,"created":0,"modified":0,"origin":666,"name":"tony-ds2","method":"POST","protocol":"HTTP","address":"localhost","port":51,"path":"/api/v1/callback","publisher":null,"user":null,"password":null,"topic":null}' http://localhost:48081/api/v1/addressable)
$ echo $STATUS

2) Make the same request again
$ echo $STATUS
Improper data: Name is not unique: tony-ds2 org.edgexfoundry.exception.controller.DataValidationException: Improper data: Name is not unique: tony-ds2 at org.edgexfoundry.controller.AddressableController.add(AddressableController.java:228) at 
.
.
.
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745) 409

**Comment by jpwhitemn** [comment]
This is actually due to the way LocalErrorController was programmed with all services in its request to getErrorAttributes with includeStackTrace set to "true" by default.  As I "harden" each of the services I am making the change to make this a config option called "print.stacktrace" where it is set to false for Docker containers, but true for dev/test in application.properties.
